let C = {
  ashp_ctrl_ip: "192.168.33.2",
  ashp_power_ip: "192.168.1.69",
  imm_ip: "192.168.1.131",
  shower_pump_ip: "192.168.1.76",

  plant_tick_ms: 10000,
  ext_refresh_ms: 20 * 60 * 1000,
  remote_poll_ms: 15000,

  ch_ttl_s: 90,
  dhw_soft_delay_s: 45 * 60,
  dhw_hard_delay_s: 3 * 60 * 60,
  urgent_top_pipe_c: 44.0,
  urgent_after_shower_s: 20 * 60,
  shower_soon_window_s: 30 * 60,

  ashp_min_off_s: 15 * 60,
  ch_min_on_s: 45 * 60,

  imm_panic_after_s: 10 * 60,
  imm_hygiene_max_s: 2 * 60 * 60,
  imm_done_below_w: 50,
  imm_done_below_s: 30,

  hygiene_pref_after_s: 5 * 24 * 3600,
  hygiene_force_after_s: 10 * 24 * 3600,
  hygiene_price_p: 5.0,
  hygiene_sw: 450,
  hygiene_target_wh: 7100,

  cheap_price_p: 7.0,
  ultra_cheap_price_p: 1.1,
  solar_good_sw: 350,
  solar_strong_sw: 550,
  max_eff_discount: 0.80,
  sw_full: 700,

  flow_lpm: 7.2,
  hot_c: 42.0,
  cold_min_c: 4.0,
  cold_max_c: 8.0,

  full_wh_normal: 6200,
  full_wh_hygiene_bonus: 900,
  shower_soon_target_wh: 3300,

  pump_start_w: 25,
  pump_stop_w: 10,
  shower_gap_s: 5 * 60,

  ashp_fault_after_fail: 3,
  remote_stale_s: 90,

  octo: "https://api.octopus.energy/v1/products/AGILE-24-10-01/electricity-tariffs/E-1R-AGILE-24-10-01-A/standard-unit-rates/",
  lat: 52.2205,
  lon: 0.4643
};

let S = { mode:"AUTO", ch_need_until:0, ch_active_since:0, dhw_pending:false, dhw_pending_since:0, dhw_satisfied:false, shower_active:false, shower_above_since:0, shower_below_since:0, shower_last_active_ts:0, shower_soon_until:0, tank_wh:C.full_wh_normal, tank_bonus_wh:0, model_last_ts:0, last_satisfied_ts:0, last_hygiene_ts:0, hygiene_active:false, hygiene_phase:"", hygiene_started_ts:0, imm_below_since:0, ashp_on:false, ashp_service:"IDLE", ashp_changed_ts:0, ashp_fail_count:0, ashp_last_ok_ts:0, imm_on:false, imm_changed_ts:0, imm_last_ok_ts:0, pump_last_ok_ts:0, last_price_load_ts:0, last_solar_load_ts:0, price_base_ts:0, price_csv:"", solar_base_ts:0, solar_csv:"", last_reason:"boot", events:[] };
function nowTs(){let st=Shelly.getComponentStatus("sys");return st&&typeof st.unixtime==="number"?st.unixtime:0;} function sysTime(){let st=Shelly.getComponentStatus("sys");return st&&st.time?st.time:"";} function clamp(v,lo,hi){if(v<lo)return lo;if(v>hi)return hi;return v;} function qVal(q,k){if(!q)return null;let a=q.split("&"),i,kv;for(i=0;i<a.length;i++){kv=a[i].split("=");if(kv.length>=2&&kv[0]===k)return kv[1];}return null;} function addEvent(tag,msg){let row=nowTs()+"|"+tag+"|"+msg;S.events.push(row);while(S.events.length>40)S.events.shift();S.last_reason=tag+(msg?(" "+msg):"");print("PLANT",row);} function saveSmall(){let obj={mode:S.mode,dhw_pending:S.dhw_pending,dhw_pending_since:S.dhw_pending_since,tank_wh:Math.round(S.tank_wh),tank_bonus_wh:Math.round(S.tank_bonus_wh),model_last_ts:S.model_last_ts,last_satisfied_ts:S.last_satisfied_ts,last_hygiene_ts:S.last_hygiene_ts,shower_last_active_ts:S.shower_last_active_ts,shower_soon_until:S.shower_soon_until,last_price_load_ts:S.last_price_load_ts,last_solar_load_ts:S.last_solar_load_ts,price_base_ts:S.price_base_ts,solar_base_ts:S.solar_base_ts,last_reason:S.last_reason};Script.storage.setItem("st",JSON.stringify(obj));Script.storage.setItem("pcsv",S.price_csv);Script.storage.setItem("scsv",S.solar_csv);} function loadSmall(){let s=Script.storage.getItem("st");if(typeof s==="string"){try{let o=JSON.parse(s);if(o.mode)S.mode=o.mode;S.dhw_pending=!!o.dhw_pending;S.dhw_pending_since=o.dhw_pending_since||0;S.tank_wh=typeof o.tank_wh==="number"?o.tank_wh:S.tank_wh;S.tank_bonus_wh=typeof o.tank_bonus_wh==="number"?o.tank_bonus_wh:0;S.model_last_ts=o.model_last_ts||0;S.last_satisfied_ts=o.last_satisfied_ts||0;S.last_hygiene_ts=o.last_hygiene_ts||0;S.shower_last_active_ts=o.shower_last_active_ts||0;S.shower_soon_until=o.shower_soon_until||0;S.last_price_load_ts=o.last_price_load_ts||0;S.last_solar_load_ts=o.last_solar_load_ts||0;S.price_base_ts=o.price_base_ts||0;S.solar_base_ts=o.solar_base_ts||0;if(o.last_reason)S.last_reason=o.last_reason;}catch(e){}}let p=Script.storage.getItem("pcsv");if(typeof p==="string")S.price_csv=p;let so=Script.storage.getItem("scsv");if(typeof so==="string")S.solar_csv=so;}
function httpGet(url,cb,ud){Shelly.call("HTTP.GET",{url:url,timeout:10},cb,ud);} function remoteSwitchSet(ip,on,toggleAfter){let url="http://"+ip+"/rpc/Switch.Set?id=0&on="+(on?"true":"false");if(typeof toggleAfter==="number")url+="&toggle_after="+toggleAfter;httpGet(url,null,null);} function remoteSwitchStatus(ip,cb,ud){httpGet("http://"+ip+"/rpc/Switch.GetStatus?id=0",cb,ud);} function localSwitchEnsure(id,on){let st=Shelly.getComponentStatus("switch",id);if(!st||st.output!==on)Shelly.call("Switch.Set",{id:id,on:on},null,null);} function setDiverterCH(){localSwitchEnsure(0,true);} function setDiverterDHW(){localSwitchEnsure(0,false);} function setCircOff(){localSwitchEnsure(1,false);} function tempC(id){let st=Shelly.getComponentStatus("temperature",id);if(!st||typeof st.tC!=="number")return null;return st.tC;} function inputState(id){let st=Shelly.getComponentStatus("input",id);if(!st||typeof st.state!=="boolean")return null;return st.state;} function csvArr(s){if(!s)return[];return s.split(",");} function priceAt(ts){if(!S.price_base_ts||!S.price_csv)return null;let idx=Math.floor((ts-S.price_base_ts)/1800);if(idx<0)return null;let arr=csvArr(S.price_csv);if(idx>=arr.length)return null;let v=parseInt(arr[idx],10);if(isNaN(v))return null;return v/10.0;} function solarAt(ts){if(!S.solar_base_ts||!S.solar_csv)return 0;let idx=Math.floor((ts-S.solar_base_ts)/3600);if(idx<0)return 0;let arr=csvArr(S.solar_csv);if(idx>=arr.length)return 0;let v=parseInt(arr[idx],10);if(isNaN(v))return 0;return v;} function effectivePrice(p,sw){let frac=clamp(sw/C.sw_full,0,C.max_eff_discount);return p*(1-frac);} function currentColdC(){let out=null;try{let raw=Script.storage.getItem("outside_c");if(typeof raw==="string")out=JSON.parse(raw);}catch(e){} if(typeof out!=="number")out=6;return clamp(out+1.0,C.cold_min_c,C.cold_max_c);} function showerPowerW(){let raw=Script.storage.getItem("pump_w");if(typeof raw!=="string")return null;let o;try{o=JSON.parse(raw);}catch(e){return null;}if(!o||(nowTs()-o.ts)>C.remote_stale_s)return null;return o.w;} function topPipeUrgent(){let t=tempC(102);if(typeof t!=="number")return false;return S.shower_active&&t<=C.urgent_top_pipe_c;} function getStoredJson(key){let raw=Script.storage.getItem(key);if(typeof raw!=="string")return null;try{return JSON.parse(raw);}catch(e){return null;}}
function updatePumpStatus(){remoteSwitchStatus(C.shower_pump_ip,function(res,ec,em,ud){if(ec!==0||!res||res.code!==200)return;let body;try{body=JSON.parse(res.body);}catch(e){return;}let ap=typeof body.apower==="number"?body.apower:0;Script.storage.setItem("pump_w",JSON.stringify({ts:nowTs(),w:ap}));S.pump_last_ok_ts=nowTs();},null);} function updateAshpHealth(){remoteSwitchStatus(C.ashp_ctrl_ip,function(res,ec){if(ec!==0||!res||res.code!==200)return;let body;try{body=JSON.parse(res.body);}catch(e){return;}S.ashp_last_ok_ts=nowTs();Script.storage.setItem("actrl",JSON.stringify({ts:S.ashp_last_ok_ts,on:!!body.output}));},null);remoteSwitchStatus(C.ashp_power_ip,function(res,ec){if(ec!==0||!res||res.code!==200)return;let body;try{body=JSON.parse(res.body);}catch(e){return;}Script.storage.setItem("apwr",JSON.stringify({ts:nowTs(),on:!!body.output,w:typeof body.apower==="number"?body.apower:0}));},null);remoteSwitchStatus(C.imm_ip,function(res,ec){if(ec!==0||!res||res.code!==200)return;let body;try{body=JSON.parse(res.body);}catch(e){return;}S.imm_last_ok_ts=nowTs();Script.storage.setItem("iok",JSON.stringify({ts:S.imm_last_ok_ts,on:!!body.output,w:typeof body.apower==="number"?body.apower:0}));},null);} function immPowerW(){let o=getStoredJson("iok");if(!o||(nowTs()-o.ts)>C.remote_stale_s)return null;return o.w;} function ashpHealthy(){let a=getStoredJson("actrl"),b=getStoredJson("apwr"),now=nowTs();return !!(a&&b&&(now-a.ts)<=C.remote_stale_s&&(now-b.ts)<=C.remote_stale_s);} function pricesFresh(){return !!(S.last_price_load_ts&&(nowTs()-S.last_price_load_ts)<=36*3600&&S.price_csv);} function solarFresh(){return !!(S.last_solar_load_ts&&(nowTs()-S.last_solar_load_ts)<=36*3600&&S.solar_csv);} 
function doFetchExternal(){let now=nowTs();if(!now)return;let fromIso=(new Date(now*1000)).toISOString();let toIso=(new Date((now+48*3600)*1000)).toISOString();let url1=C.octo+"?period_from="+fromIso+"&period_to="+toIso;let url2="https://api.open-meteo.com/v1/forecast?latitude="+C.lat+"&longitude="+C.lon+"&hourly=shortwave_radiation&forecast_hours=48&timeformat=unixtime&timezone=GMT";httpGet(url1,function(res,ec){if(ec!==0||!res||res.code!==200){addEvent("agile_fetch_fail",""+ec);return;}let body,arr,vals=[],i,t,ts0=0;try{body=JSON.parse(res.body);}catch(e){addEvent("agile_parse_fail","");return;}if(!body||!body.results||!body.results.length)return;arr=body.results.slice().sort(function(a,b){return new Date(a.valid_from).getTime()-new Date(b.valid_from).getTime();});ts0=Math.floor(new Date(arr[0].valid_from).getTime()/1000);for(i=0;i<arr.length;i++){t=parseInt(Math.round(arr[i].value_inc_vat*10),10);vals.push(""+t);}S.price_base_ts=ts0;S.price_csv=vals.join(",");S.last_price_load_ts=nowTs();saveSmall();addEvent("agile_cached",""+vals.length+" slots");},null);httpGet(url2,function(res,ec){if(ec!==0||!res||res.code!==200){addEvent("solar_fetch_fail",""+ec);return;}let body,vals=[],i,t0=0;try{body=JSON.parse(res.body);}catch(e){addEvent("solar_parse_fail","");return;}if(!body||!body.hourly||!body.hourly.time||!body.hourly.shortwave_radiation)return;t0=body.hourly.time[0];for(i=0;i<body.hourly.shortwave_radiation.length;i++)vals.push(""+Math.round(body.hourly.shortwave_radiation[i]));S.solar_base_ts=t0;S.solar_csv=vals.join(",");S.last_solar_load_ts=nowTs();saveSmall();addEvent("solar_cached",""+vals.length+" slots");},null);} 
function updateDhwInputs(){let call=inputState(0),sat=inputState(1),now=nowTs();if(call===true&&!S.dhw_pending){S.dhw_pending=true;S.dhw_pending_since=now;addEvent("dhw_call","latched");} if(sat===true){if(!S.dhw_satisfied)addEvent("dhw_satisfied","");S.dhw_satisfied=true;S.dhw_pending=false;S.last_satisfied_ts=now;S.tank_wh=C.full_wh_normal;if(!S.hygiene_active)S.tank_bonus_wh=0;} else {S.dhw_satisfied=false;if(!S.dhw_pending&&(S.tank_wh<2500||topPipeUrgent())){S.dhw_pending=true;S.dhw_pending_since=now;addEvent("dhw_inferred","model_low_or_toppipe");}}}
function updateShowerModel(){let now=nowTs(),pw=showerPowerW();if(typeof pw==="number"){if(!S.shower_active){if(pw>=C.pump_start_w){if(!S.shower_above_since)S.shower_above_since=now;if((now-S.shower_above_since)>=10){S.shower_active=true;S.shower_last_active_ts=now;S.shower_below_since=0;addEvent("shower_start","pump="+pw);}} else S.shower_above_since=0;} else {if(pw>C.pump_stop_w){S.shower_last_active_ts=now;S.shower_below_since=0;} else {if(!S.shower_below_since)S.shower_below_since=now;if((now-S.shower_below_since)>=C.shower_gap_s){S.shower_active=false;S.shower_above_since=0;S.shower_below_since=0;addEvent("shower_end","");}}}}}
function standingLossW(){let frac=clamp((S.tank_wh+S.tank_bonus_wh)/(C.full_wh_normal+C.full_wh_hygiene_bonus),0,1);let temp=45+(20*frac);if(temp<=45)return 1240/24;if(temp<=50)return (1240+(temp-45)*((1490-1240)/5))/24;if(temp<=55)return (1490+(temp-50)*((1740-1490)/5))/24;return (1740+(temp-55)*((2230-1740)/10))/24;} function updateEnergyModel(){let now=nowTs();if(!now)return;if(!S.model_last_ts){S.model_last_ts=now;return;}let dt=now-S.model_last_ts;if(dt<=0)return;S.model_last_ts=now;let lossWh=standingLossW()*(dt/3600.0);S.tank_wh=Math.max(0,S.tank_wh-lossWh);if(S.shower_active){let cold=currentColdC();let powerW=(C.flow_lpm*4.186*(C.hot_c-cold)*1000.0)/60.0/3.6;let drawWh=powerW*(dt/3600.0);S.tank_wh=Math.max(0,S.tank_wh-drawWh);}} function hygieneDueState(){let now=nowTs();if(!S.last_hygiene_ts)return "FORCE";let age=now-S.last_hygiene_ts;if(age>=C.hygiene_force_after_s)return "FORCE";if(age>=C.hygiene_pref_after_s)return "PREFER";return "NO";} function hygieneGoodSlot(){let now=nowTs(),p=priceAt(now),sw=solarAt(now);if(sw>=C.hygiene_sw)return true;if(p!==null&&p<=C.hygiene_price_p)return true;return false;} function bestEffUntil(deadlineTs){let now=nowTs();if(!pricesFresh()||!solarFresh())return null;let best=null,ts;for(ts=now;ts<=deadlineTs;ts+=1800){let p=priceAt(ts);if(p===null)continue;let sw=solarAt(ts);let eff=effectivePrice(p,sw);if(best===null||eff<best.eff)best={ts:ts,p:p,sw:sw,eff:eff};}return best;} function shouldPreferImmersionNow(){let p=priceAt(nowTs());if(p===null)return false;return p<=C.ultra_cheap_price_p;} function chooseSoonDhw(){let now=nowTs(),age=S.dhw_pending_since?(now-S.dhw_pending_since):0,p=priceAt(now),sw=solarAt(now),eff=p===null?999:effectivePrice(p,sw),urgent=false,deadline,best;if(S.shower_active)urgent=true;if((now-S.shower_last_active_ts)<=C.urgent_after_shower_s)urgent=true;if(topPipeUrgent())urgent=true;if(S.tank_wh<=1500)urgent=true;if(S.shower_soon_until>now&&S.tank_wh<C.shower_soon_target_wh)urgent=true;if(age>=C.dhw_hard_delay_s)urgent=true;if(urgent)return true;if(!pricesFresh()||!solarFresh())return age>=C.dhw_soft_delay_s;if(sw>=C.solar_strong_sw)return true;if(eff<=C.cheap_price_p)return true;deadline=S.dhw_pending_since+C.dhw_hard_delay_s;best=bestEffUntil(deadline);if(best&&now>=best.ts&&now<(best.ts+1800))return true;if(age>=C.dhw_soft_delay_s){if(!best)return true;if(best.ts-now>2*3600)return true;if(eff<=(best.eff+0.5))return true;return false;}return false;}
function startAshp(service,urgent){let now=nowTs(),offAge=S.ashp_changed_ts?(now-S.ashp_changed_ts):999999;if(!S.ashp_on){if(!urgent&&offAge<C.ashp_min_off_s)return false;remoteSwitchSet(C.ashp_ctrl_ip,true);S.ashp_on=true;S.ashp_service=service;S.ashp_changed_ts=now;if(service==="CH")S.ch_active_since=now;addEvent("ashp_on",service+(urgent?" urgent":""));return true;} if(S.ashp_service!==service){S.ashp_service=service;if(service==="CH")S.ch_active_since=now;addEvent("ashp_service",service);} return true;} function stopAshp(force){let now=nowTs();if(!S.ashp_on)return true;if(!force&&S.ashp_service==="CH"&&S.ch_active_since&&(now-S.ch_active_since)<C.ch_min_on_s)return false;remoteSwitchSet(C.ashp_ctrl_ip,false);S.ashp_on=false;S.ashp_service="IDLE";S.ashp_changed_ts=now;addEvent("ashp_off",force?"forced":"");return true;} function setImm(on,why){if(S.imm_on===on)return;remoteSwitchSet(C.imm_ip,on);S.imm_on=on;S.imm_changed_ts=nowTs();addEvent(on?"imm_on":"imm_off",why||"");} function maybeFinishHygiene(){if(!S.hygiene_active)return;let now=nowTs(),w=immPowerW();if(S.imm_on&&typeof w==="number"&&w<C.imm_done_below_w){if(!S.imm_below_since)S.imm_below_since=now;if((now-S.imm_below_since)>=C.imm_done_below_s){S.hygiene_active=false;S.hygiene_phase="";S.last_hygiene_ts=now;S.tank_bonus_wh=C.full_wh_hygiene_bonus;setImm(false,"hygiene_done");saveSmall();addEvent("hygiene_done","thermostat_cut");}} else S.imm_below_since=0;if(S.hygiene_active&&(now-S.hygiene_started_ts)>=C.imm_hygiene_max_s){S.hygiene_active=false;S.hygiene_phase="";S.last_hygiene_ts=now;setImm(false,"hygiene_timeout");saveSmall();addEvent("hygiene_done","timeout");}} function startHygiene(){if(!S.hygiene_active){S.hygiene_active=true;S.hygiene_phase="PREHEAT";S.hygiene_started_ts=nowTs();S.imm_below_since=0;addEvent("hygiene_start","");}} function shouldPanicImmersion(){let now=nowTs();if(ashpHealthy()){S.ashp_fail_count=0;return false;}S.ashp_fail_count++;if(S.ashp_fail_count<C.ashp_fault_after_fail)return false;if(S.hygiene_active)return true;if(S.shower_active)return true;if(S.dhw_pending&&S.dhw_pending_since&&(now-S.dhw_pending_since)>=C.imm_panic_after_s)return true;if(topPipeUrgent())return true;return false;} function maybeSetShowerSoonHint(){if(S.shower_soon_until&&S.shower_soon_until<nowTs()){S.shower_soon_until=0;addEvent("shower_soon_clear","expired");}}
function plantLoop(){let now=nowTs();if(!now)return;updateDhwInputs();updateShowerModel();updateEnergyModel();maybeFinishHygiene();maybeSetShowerSoonHint();let chNeed=now<S.ch_need_until;let due=hygieneDueState();if(due!=="NO"&&(due==="FORCE"||hygieneGoodSlot()))startHygiene();let needDhwNow=(S.dhw_pending&&chooseSoonDhw())||S.hygiene_active||(S.shower_soon_until>now&&S.tank_wh<C.shower_soon_target_wh);let panicImm=shouldPanicImmersion();let ultraCheapImm=shouldPreferImmersionNow();setCircOff();if(S.hygiene_active){if(S.hygiene_phase==="PREHEAT"){if(!S.dhw_satisfied&&S.tank_wh<C.hygiene_target_wh){if(ultraCheapImm){setDiverterCH();stopAshp(true);setImm(true,"ultra_cheap_preheat");saveSmall();return;}setDiverterDHW();if(ashpHealthy())startAshp("DHW",true);else S.hygiene_phase="IMMERSION";} else S.hygiene_phase="IMMERSION";} if(S.hygiene_phase==="IMMERSION"){setDiverterCH();stopAshp(true);setImm(true,"hygiene");saveSmall();return;}}
if(panicImm){setDiverterCH();stopAshp(true);setImm(true,"panic");saveSmall();return;} if(needDhwNow){if(ultraCheapImm){setDiverterCH();stopAshp(true);setImm(true,"ultra_cheap_dhw");saveSmall();return;} setImm(false,"dhw_ashp_pref");setDiverterDHW();if(ashpHealthy())startAshp("DHW",true);else setImm(true,"ashp_fault_dhw");saveSmall();return;} setImm(false,"no_need");setDiverterCH();if(chNeed&&ashpHealthy())startAshp("CH",false);else stopAshp(false);saveSmall();}
function endpoint(req,res){let mode=qVal(req.query,"mode"),ch=qVal(req.query,"ch"),status=qVal(req.query,"status"),outside=qVal(req.query,"outside"),ev=qVal(req.query,"event"),showerSoon=qVal(req.query,"showersoon");if(mode!==null)S.mode=mode;if(outside!==null){let v=parseFloat(outside);if(!isNaN(v))Script.storage.setItem("outside_c",JSON.stringify(v));} if(showerSoon!==null){if(showerSoon==="1"||showerSoon==="true"){S.shower_soon_until=nowTs()+C.shower_soon_window_s;addEvent("shower_soon_set","30m");} else {S.shower_soon_until=0;addEvent("shower_soon_clear","manual");}} if(ch!==null){if(ch==="1"||ch==="true")S.ch_need_until=nowTs()+C.ch_ttl_s;else S.ch_need_until=0;} if(ev!==null)addEvent("remote",ev); if(status==="1"){let body={now:nowTs(),time:sysTime(),mode:S.mode,ch_need:nowTs()<S.ch_need_until,dhw_pending:S.dhw_pending,dhw_satisfied:S.dhw_satisfied,shower_active:S.shower_active,shower_soon:S.shower_soon_until>nowTs(),tank_wh:Math.round(S.tank_wh),tank_bonus_wh:Math.round(S.tank_bonus_wh),ashp_on:S.ashp_on,ashp_service:S.ashp_service,ashp_healthy:ashpHealthy(),imm_on:S.imm_on,prefer_immersion_now:shouldPreferImmersionNow(),hygiene_active:S.hygiene_active,hygiene_phase:S.hygiene_phase,hygiene_due:hygieneDueState(),cur_price_p:priceAt(nowTs()),cur_sw:solarAt(nowTs()),last_reason:S.last_reason,top_pipe_c:tempC(102),common_feed_c:tempC(100),ch_branch_c:tempC(101),events:S.events};res.code=200;res.headers=[["Content-Type","application/json"]];res.body=JSON.stringify(body);res.send();return;} res.code=200;res.body="OK";res.send();}
loadSmall();HTTPServer.registerEndpoint("plant",endpoint);setDiverterCH();setCircOff();Timer.set(C.plant_tick_ms,true,plantLoop);Timer.set(C.remote_poll_ms,true,function(){updatePumpStatus();updateAshpHealth();});Timer.set(C.ext_refresh_ms,true,doFetchExternal);doFetchExternal();updatePumpStatus();updateAshpHealth();addEvent("plant_started","script="+Shelly.getCurrentScriptId());
